FROM node

ENV WORKDIR /usr/src/app
RUN npm i --registry=https://registry.npm.taobao.org -g cnpm

RUN mkdir -p $WORKDIR
WORKDIR $WORKDIR
EXPOSE 2333 8080

COPY package.json $WORKDIR
RUN cnpm i
RUN rm -f package.json

VOLUME $WORKDIR $WORKDIR/data $WORKDIR/node_modules

CMD npm run dev